name = "LuxorLayout"
uuid = "909dfbbc-cb73-418e-9556-eed3773b40ca"
authors = ["hustf <hustf@users.noreply.github.com> and contributors"]
version = "0.0.9"

[deps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"
Pango_jll = "36c8627f-9965-5494-a995-c6b170f724f3"
ThreadPools = "b189fb0b-2eb5-4ed4-bc0c-d34c51242431"

# NOTE, we have QuadGK as a dependency because of the test
# file snowblind_test.jl. That's it. Test only dependencies
# are cumbersome for development testing. But this could be dropped!
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"


[compat]
julia = "1.9"
Pango_jll = "=1.42.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
